### ISSUE TITLE
出現ModuleNotFoundError: No module named 'utilities',請問如何處理

### ISSUE THREAD

**Issue by hkjeff** [Jack-cky/HKJC_Horse_Race_Record_Scraping#1]
你好JACK
運行時出現
line 24, in <module>
    import utilities
ModuleNotFoundError: No module named 'utilities'

請問如何處理?謝謝
Jeff

**Comment by Jack-cky** [comment]
Halo Jeff! Thanks for reporting the issue!
I forgot to upload the utilities.py in the previous commit. You may try it again.
